Repository commercetools/commercetools-sdk-typescript, pull requests merged in 2024-06, with the labels that each got.

#732 feat(customMiddleware): add test for custom middleware
  packages/platform-sdk/test/integration-tests/sdk-v3/middlewares.test.ts
Labels: missing-jira, 1 min review

#714 feat(abortController): add retry on abort
  packages/platform-sdk/test/integration-tests/sdk-v3/error-cases.test.ts
  packages/sdk-client-v3/src/types/types.d.ts
  packages/sdk-client-v3/src/utils/executor.ts
  packages/sdk-client-v3/src/utils/validate.ts
  packages/sdk-client-v3/tests/http.test/http-middleware.test.ts
Labels: missing-jira, 20 min review

#738 Increase Jest Max Worker
  package.json
Labels: missing-jira
